# Generated by Django 5.0.6 on 2026-05-30 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('hijri_month', models.PositiveSmallIntegerField()),
                ('hijri_year', models.PositiveIntegerField()),
                ('hijri_display', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SSC_investments',
                'ordering': ['-hijri_year', '-hijri_month'],
            },
        ),
        migrations.CreateModel(
            name='ProfitDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit_percentage', models.DecimalField(decimal_places=2, help_text='e.g. 10.00 for 10%', max_digits=5)),
                ('total_profit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('hijri_month', models.PositiveSmallIntegerField()),
                ('hijri_year', models.PositiveIntegerField()),
                ('hijri_display', models.CharField(max_length=50)),
                ('is_distributed', models.BooleanField(default=False)),
                ('distributed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('distributed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='investments.investment')),
            ],
            options={
                'db_table': 'SSC_profit_distributions',
                'ordering': ['-hijri_year'],
            },
        ),
    ]
