# Generated by Django 6.0.5 on 2026-05-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termlyduescycle',
            name='name',
            field=models.CharField(help_text="e.g. 'First Term 1446'", max_length=100),
        ),
    ]
