# Generated by Django 6.0.5 on 2026-06-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_alter_termlyduescycle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsledger',
            name='entry_type',
            field=models.CharField(choices=[('ordinary_savings', 'Ordinary Savings'), ('termly_dues', 'Termly Dues'), ('profit_share', 'Profit Share'), ('adjustment', 'Adjustment'), ('legacy_import', 'Legacy Import'), ('loan_repayment', 'Loan Repayment'), ('loan_disbursement', 'Loan Disbursement')], max_length=30),
        ),
    ]
