# Generated by Django 5.0.6 on 2026-06-05 19:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0003_alter_savingsledger_entry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberbalance',
            name='special_savings',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
    ]
