# Generated by Django 5.0.6 on 2026-06-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0004_memberbalance_special_savings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsledger',
            name='entry_type',
            field=models.CharField(choices=[('ordinary_savings', 'Ordinary Savings'), ('termly_dues', 'Termly Dues'), ('profit_share', 'Profit Share'), ('adjustment', 'Adjustment'), ('legacy_import', 'Legacy Import'), ('loan_repayment', 'Loan Repayment'), ('loan_disbursement', 'Loan Disbursement'), ('special_savings', 'Special Fixed Savings')], max_length=30),
        ),
    ]
