# Generated by Django 5.0.6 on 2026-05-30 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('savings_posted', 'Savings Posted'), ('loan_submitted', 'Loan Application Submitted'), ('loan_approved', 'Loan Approved'), ('loan_rejected', 'Loan Rejected'), ('loan_hos_approved', 'Loan Final Approval'), ('surety_request', 'Surety Request'), ('surety_confirmed', 'Surety Confirmed'), ('surety_declined', 'Surety Declined'), ('repayment_posted', 'Repayment Posted'), ('loan_completed', 'Loan Completed'), ('dues_posted', 'Dues Posted'), ('savings_change', 'Savings Change Request'), ('profit_distributed', 'Profit Distributed')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('related_id', models.PositiveIntegerField(blank=True, help_text='Related object pk', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SMS_notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
