# Generated by Django 6.0.5 on 2026-05-30 09:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loan_configuration_extra_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='proposed_duration_months',
            field=models.PositiveSmallIntegerField(help_text='Maximum repayment duration in months, as configured by loan rules.'),
        ),
        migrations.AlterField(
            model_name='loanconfiguration',
            name='max_loan_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum loan amount allowed. Set 0 for no limit.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='loanconfiguration',
            name='min_loan_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000.00'), help_text='Minimum loan amount allowed.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='loanconfiguration',
            name='self_surety_ratio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.75'), help_text='Fraction of available balance a member may borrow.', max_digits=4),
        ),
    ]
