# Generated by Django 6.0.5 on 2026-06-02 20:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_alter_loanapplication_proposed_duration_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanconfiguration',
            name='max_borrowable_ratio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.75'), help_text='Absolute maximum borrowable as a fraction of available balance (e.g. 1.00 for 100%).', max_digits=4),
        ),
    ]
