# Generated by Django 6.0.5 on 2026-06-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_loanconfiguration_max_borrowable_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='admin_final_approval_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('pending_sureties', 'Pending Surety Confirmation'), ('approved', 'Committee Approved'), ('pending_admin', 'Pending Admin Approval'), ('hos_approved', 'HOS Approved — Active'), ('active', 'Active'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('defaulted', 'Defaulted')], default='submitted', max_length=20),
        ),
    ]
