# Generated by Django 5.0.6 on 2026-06-03 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_is_new_member_to_memberprofile'),
        ('loans', '0006_loanapplication_admin_final_approval_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan_draft', to='accounts.memberprofile')),
            ],
            options={
                'db_table': 'SSC_loan_drafts',
            },
        ),
    ]
