# Generated by Django 5.0.6 on 2026-06-05 11:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_loandraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanconfiguration',
            name='external_surety_max_ratio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.75'), help_text="Maximum fraction of a surety's available balance they can guarantee.", max_digits=4),
        ),
    ]
