# Generated by Django 5.0.6 on 2026-06-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_set_max_repayment_12'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanconfiguration',
            name='max_repayment_months',
            field=models.PositiveSmallIntegerField(default=12, help_text='Maximum allowed repayment duration in months.'),
        ),
    ]
