# Generated by Django 5.0.6 on 2026-06-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0010_alter_loanconfiguration_max_repayment_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanconfiguration',
            name='default_termly_dues',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Default amount for termly dues.', max_digits=12),
        ),
        migrations.AddField(
            model_name='loanconfiguration',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly interest rate in % applied to outstanding balance.', max_digits=5),
        ),
        migrations.AddField(
            model_name='loanconfiguration',
            name='late_repayment_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Flat fee charged for late repayment.', max_digits=12),
        ),
        migrations.AddField(
            model_name='loanconfiguration',
            name='max_active_loans',
            field=models.PositiveSmallIntegerField(default=1, help_text='Maximum number of active loans a member can have simultaneously.'),
        ),
        migrations.AddField(
            model_name='loanconfiguration',
            name='min_savings_contribution',
            field=models.DecimalField(decimal_places=2, default=1000.0, help_text='Minimum monthly savings contribution amount.', max_digits=12),
        ),
        migrations.AddField(
            model_name='loanconfiguration',
            name='repayment_grace_days',
            field=models.PositiveSmallIntegerField(default=0, help_text='Days allowed after due date before late fee applies.'),
        ),
    ]
