# Generated by Django 5.0.6 on 2026-06-20 05:19

from decimal import Decimal
from django.db import migrations, models

def update_existing_config(apps, schema_editor):
    LoanConfiguration = apps.get_model('loans', 'LoanConfiguration')
    LoanConfiguration.objects.update(
        self_surety_ratio=Decimal('1.00'),
        max_borrowable_ratio=Decimal('1.00')
    )

class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0011_loanconfiguration_default_termly_dues_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanconfiguration',
            name='max_borrowable_ratio',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Absolute maximum borrowable as a fraction of available balance (e.g. 1.00 for 100%).', max_digits=4),
        ),
        migrations.AlterField(
            model_name='loanconfiguration',
            name='self_surety_ratio',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Fraction of available balance a member may borrow without external sureties.', max_digits=4),
        ),
        migrations.RunPython(update_existing_config),
    ]