# Generated by Django 5.0.6 on 2026-06-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0012_update_ratios_to_100'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanconfiguration',
            name='reapplication_cooldown_hours',
            field=models.PositiveIntegerField(default=12, help_text='Hours a member must wait after a rejection or withdrawal before reapplying.'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('pending_sureties', 'Pending Surety Confirmation'), ('approved', 'Committee Approved'), ('pending_admin', 'Pending Admin Approval'), ('hos_approved', 'HOS Approved — Active'), ('active', 'Active'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('defaulted', 'Defaulted'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=20),
        ),
    ]
