# Generated by Django 6.0.5 on 2026-05-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='consecutive_savings_months',
            field=models.PositiveIntegerField(default=0, help_text='Resets to 0 when a month is missed. Requirement is governed by admin-configured loan rules.'),
        ),
    ]
