# Generated by Django 5.0.6 on 2026-06-01 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_memberprofile_consecutive_savings_months'),
        ('accounts', '0006_add_superuser'),
    ]

    operations = [
    ]
