# Generated by Django 6.0.5 on 2026-06-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_merge_20260601_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='is_new_member',
            field=models.BooleanField(
                default=False,
                help_text='Indicates a new member who has not yet completed the introductory contribution period.',
            ),
        ),
    ]
