# Generated by Django 5.0.6 on 2026-06-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_is_new_member_to_memberprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='is_special_saver',
            field=models.BooleanField(default=False),
        ),
    ]
