# Generated by Django 5.0.6 on 2026-06-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_memberprofile_is_special_saver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='email_address',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Email Address'),
        ),
    ]
