# Generated by Django 5.0.6 on 2026-06-23 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_memberprofile_email_address'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='staffidregistry',
            table='ssc_staff_id_registry',
        ),
    ]
