# Generated by Django 5.0.6 on 2026-06-23 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_staffidregistry_table'),
    ]

    operations = [
    ]
