# Generated by Django 5.0.6 on 2026-06-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_empty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='school_branch',
            field=models.CharField(choices=[('primary', 'Primary'), ('college', 'College'), ('riyaad_elementary', 'Riyaad Elementary'), ('riyaad_college', 'Riyaad College'), ('other', 'Other')], max_length=20),
        ),
    ]
